import Link from "next/link";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <nav>
      <ul className={styles.ul}>
        <li>
          <Link href="/products/women"> 여성옷</Link>
        </li>
        <li>
          <Link href="/products/man">남성옷</Link>{" "}
        </li>
      </ul>
      <section>{children}</section>
    </nav>
  );
}
